name: flutter_image_filters
description: Image filters based on OpenGL(SPIR-V) fragment shaders with useful preview widgets
version: 0.0.3
homepage: https://github.com/nikolaydymura/flutter_image_filters
repository: https://github.com/nikolaydymura/flutter_image_filters
platforms:
  android:
  ios:
  macos:

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_gpu_filters_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  image: ^3.2.2

flutter:
