name: flutter_image_filters

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze lib

      - name: Run tests
        run: flutter test --no-pub --coverage

      - name: Format tests
        run: | 
          flutter pub global activate remove_from_coverage
          remove_from_coverage -f coverage/lcov.info -r '\bshaders\b'

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: coverage/lcov.info
          min_coverage: 80
          exclude: 'shaders/'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  pana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0

      - name: Install Dependencies
        run: |
          flutter packages get
          flutter pub global activate pana
      - name: Verify Pub Score
        run: |
          PANA=$(pana . --no-warning); PANA_SCORE=$(echo $PANA | sed -n "s/.*Points: \([0-9]*\)\/\([0-9]*\)./\1\/\2/p")
          echo "score: $PANA_SCORE"
          IFS='/'; read -a SCORE_ARR <<< "$PANA_SCORE"; SCORE=SCORE_ARR[0]; TOTAL=SCORE_ARR[1]
          if [ -z "$1" ]; then MINIMUM_SCORE=TOTAL; else MINIMUM_SCORE=$1; fi
          if (( $SCORE < $MINIMUM_SCORE )); then echo "minimum score $MINIMUM_SCORE was not met!"; exit 1; fi


  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          name: "GLSL sources 0.1.0"
          tag: "v0.1.0"
          artifacts: "shaders/brightness.glsl,shaders/color_invert.glsl,shaders/color_matrix.glsl,shaders/contrast.glsl,shaders/exposure.glsl,shaders/false_color.glsl,shaders/gamma.glsl,shaders/grayscale.glsl,shaders/halftone.glsl,shaders/luminance.glsl,shaders/luminance_threshold.glsl,shaders/monochrome.glsl,shaders/opacity.glsl,shaders/posterize.glsl,shaders/rgb.glsl,shaders/saturation.glsl,shaders/solarize.glsl"